/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedCheckAuthRouteImport } from './routes/(authenticated)/_checkAuth'
import { Route as authenticatedCheckAuthGuidesRouteImport } from './routes/(authenticated)/_checkAuth.guides'
import { Route as authenticatedCheckAuthDashboardRouteImport } from './routes/(authenticated)/_checkAuth.dashboard'
import { Route as authenticatedCheckAuthGuidesIndexRouteImport } from './routes/(authenticated)/_checkAuth.guides.index'
import { Route as authenticatedCheckAuthGuidesCreateRouteImport } from './routes/(authenticated)/_checkAuth.guides.create'
import { Route as authenticatedCheckAuthGuidesGuideIdRouteImport } from './routes/(authenticated)/_checkAuth.guides.$guideId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedCheckAuthRoute = authenticatedCheckAuthRouteImport.update({
  id: '/(authenticated)/_checkAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedCheckAuthGuidesRoute =
  authenticatedCheckAuthGuidesRouteImport.update({
    id: '/guides',
    path: '/guides',
    getParentRoute: () => authenticatedCheckAuthRoute,
  } as any)
const authenticatedCheckAuthDashboardRoute =
  authenticatedCheckAuthDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedCheckAuthRoute,
  } as any)
const authenticatedCheckAuthGuidesIndexRoute =
  authenticatedCheckAuthGuidesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedCheckAuthGuidesRoute,
  } as any)
const authenticatedCheckAuthGuidesCreateRoute =
  authenticatedCheckAuthGuidesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => authenticatedCheckAuthGuidesRoute,
  } as any)
const authenticatedCheckAuthGuidesGuideIdRoute =
  authenticatedCheckAuthGuidesGuideIdRouteImport.update({
    id: '/$guideId',
    path: '/$guideId',
    getParentRoute: () => authenticatedCheckAuthGuidesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authenticatedCheckAuthDashboardRoute
  '/guides': typeof authenticatedCheckAuthGuidesRouteWithChildren
  '/guides/$guideId': typeof authenticatedCheckAuthGuidesGuideIdRoute
  '/guides/create': typeof authenticatedCheckAuthGuidesCreateRoute
  '/guides/': typeof authenticatedCheckAuthGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authenticatedCheckAuthDashboardRoute
  '/guides/$guideId': typeof authenticatedCheckAuthGuidesGuideIdRoute
  '/guides/create': typeof authenticatedCheckAuthGuidesCreateRoute
  '/guides': typeof authenticatedCheckAuthGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/(authenticated)/_checkAuth': typeof authenticatedCheckAuthRouteWithChildren
  '/(authenticated)/_checkAuth/dashboard': typeof authenticatedCheckAuthDashboardRoute
  '/(authenticated)/_checkAuth/guides': typeof authenticatedCheckAuthGuidesRouteWithChildren
  '/(authenticated)/_checkAuth/guides/$guideId': typeof authenticatedCheckAuthGuidesGuideIdRoute
  '/(authenticated)/_checkAuth/guides/create': typeof authenticatedCheckAuthGuidesCreateRoute
  '/(authenticated)/_checkAuth/guides/': typeof authenticatedCheckAuthGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/guides'
    | '/guides/$guideId'
    | '/guides/create'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/guides/$guideId'
    | '/guides/create'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/(authenticated)/_checkAuth'
    | '/(authenticated)/_checkAuth/dashboard'
    | '/(authenticated)/_checkAuth/guides'
    | '/(authenticated)/_checkAuth/guides/$guideId'
    | '/(authenticated)/_checkAuth/guides/create'
    | '/(authenticated)/_checkAuth/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  authenticatedCheckAuthRoute: typeof authenticatedCheckAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/_checkAuth': {
      id: '/(authenticated)/_checkAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedCheckAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/_checkAuth/guides': {
      id: '/(authenticated)/_checkAuth/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof authenticatedCheckAuthGuidesRouteImport
      parentRoute: typeof authenticatedCheckAuthRoute
    }
    '/(authenticated)/_checkAuth/dashboard': {
      id: '/(authenticated)/_checkAuth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedCheckAuthDashboardRouteImport
      parentRoute: typeof authenticatedCheckAuthRoute
    }
    '/(authenticated)/_checkAuth/guides/': {
      id: '/(authenticated)/_checkAuth/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof authenticatedCheckAuthGuidesIndexRouteImport
      parentRoute: typeof authenticatedCheckAuthGuidesRoute
    }
    '/(authenticated)/_checkAuth/guides/create': {
      id: '/(authenticated)/_checkAuth/guides/create'
      path: '/create'
      fullPath: '/guides/create'
      preLoaderRoute: typeof authenticatedCheckAuthGuidesCreateRouteImport
      parentRoute: typeof authenticatedCheckAuthGuidesRoute
    }
    '/(authenticated)/_checkAuth/guides/$guideId': {
      id: '/(authenticated)/_checkAuth/guides/$guideId'
      path: '/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof authenticatedCheckAuthGuidesGuideIdRouteImport
      parentRoute: typeof authenticatedCheckAuthGuidesRoute
    }
  }
}

interface authenticatedCheckAuthGuidesRouteChildren {
  authenticatedCheckAuthGuidesGuideIdRoute: typeof authenticatedCheckAuthGuidesGuideIdRoute
  authenticatedCheckAuthGuidesCreateRoute: typeof authenticatedCheckAuthGuidesCreateRoute
  authenticatedCheckAuthGuidesIndexRoute: typeof authenticatedCheckAuthGuidesIndexRoute
}

const authenticatedCheckAuthGuidesRouteChildren: authenticatedCheckAuthGuidesRouteChildren =
  {
    authenticatedCheckAuthGuidesGuideIdRoute:
      authenticatedCheckAuthGuidesGuideIdRoute,
    authenticatedCheckAuthGuidesCreateRoute:
      authenticatedCheckAuthGuidesCreateRoute,
    authenticatedCheckAuthGuidesIndexRoute:
      authenticatedCheckAuthGuidesIndexRoute,
  }

const authenticatedCheckAuthGuidesRouteWithChildren =
  authenticatedCheckAuthGuidesRoute._addFileChildren(
    authenticatedCheckAuthGuidesRouteChildren,
  )

interface authenticatedCheckAuthRouteChildren {
  authenticatedCheckAuthDashboardRoute: typeof authenticatedCheckAuthDashboardRoute
  authenticatedCheckAuthGuidesRoute: typeof authenticatedCheckAuthGuidesRouteWithChildren
}

const authenticatedCheckAuthRouteChildren: authenticatedCheckAuthRouteChildren =
  {
    authenticatedCheckAuthDashboardRoute: authenticatedCheckAuthDashboardRoute,
    authenticatedCheckAuthGuidesRoute:
      authenticatedCheckAuthGuidesRouteWithChildren,
  }

const authenticatedCheckAuthRouteWithChildren =
  authenticatedCheckAuthRoute._addFileChildren(
    authenticatedCheckAuthRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  authenticatedCheckAuthRoute: authenticatedCheckAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
